### ISSUE TITLE
Not working after 9/18 release

### ISSUE THREAD

**Issue by blinksoft** [EvilHacker/BoxJoint#10]
Looks like a lot of plugins were blown up after the 9/18/2024 release.   This plugin doesn't throw an error, but the first thing that I saw was a drawing I opened that use to work, now causes the expansion of the group and then nothing is working, deleting those and then trying to recreate them does not work, as when the dialog box opens, there is nothing but the the selection of the faces, no other settings are shown.   Any help is appreciated.

**Comment by EvilHacker** [comment]
This has been fixed in version 1.0.3: https://github.com/EvilHacker/BoxJoint/releases/tag/v1.0.3 .

The Autodesk App should be updated in a few days.
