### ISSUE TITLE
Parametric breaks bodies and joins

### ISSUE THREAD

**Issue by XanthiaJo** [EvilHacker/BoxJoint#14]
Such a useful tool however I'm running into a problem with the parametric side of things. As soon as I change a parameter (example is height), it just goes splat. Unfortunately my coding is incredibly basic and can't really work out what's what myself. Any advice appreciated 

![image](https://github.com/user-attachments/assets/60cbb523-2c1e-4dab-896b-e840d5c2ec82)

![image](https://github.com/user-attachments/assets/2d03f5cb-77fa-4d7e-bd29-d52d9620b4fd)

![image](https://github.com/user-attachments/assets/ddca4e3c-b422-4c31-8f81-8a060be97e7a)

**Comment by EvilHacker** [comment]
Could you share a simple model that exhibits this problem? This would be helpful for me to bug the problem. Thanks

**Comment by XanthiaJo** [comment]
Here is the above stripped down to just the outside box. The relevant parametric values are favourited. Thanks muchly

[Box w script v2.zip](https://github.com/user-attachments/files/17918962/Box.w.script.v2.zip)

**Comment by EvilHacker** [comment]
I think this is related to a known issue where the Add-In doesn't work on bodies in different components: https://github.com/EvilHacker/BoxJoint/issues/2#issuecomment-1987001559 .

I'm not sure why this is happening in your model. You are not selecting bodies in different components but just the presence of other components seems to induce this problem too.

I exported the single component that contains your box and am able to change parameters with no problem.

Right now, I don't know how to fix this.

I have successfully used the Box Join Add-In in a model without components first and then created components out of the bodies. I could modify parameters without problem.

I'm not sure if it is practical for you to work this way – use Box Join Add-In without components first, then create components after?

**Comment by XanthiaJo** [comment]
Thank you for looking. I did notice the different component bug, and like you, I thought that being in the same component it would be fine. I will continue to play and keep this in mind. Curious to know if it handles mirrored bodies ok after all lol. The way Fusion handles bodies/components is so odd!
