### ISSUE TITLE
I can't get this new release to work!

### ISSUE THREAD

**Issue by Khey426** [EvilHacker/BoxJoint#6]
I used the previous version and it worked perfectly! I've got the new version loaded and available in Fusion but when I try to create a joint it simply does nothing. I open up the function, choose the two bodies, the "direction" (whatever that is) and then I've tried every combination I think of with regards to finger style, size direction etc.... but absolutely nothing happens when I click OK. Nothing shows in the timeline, no fingers appear nothing. Anyone know what I'm doing wrong?

<img width="1920" alt="Screenshot 2024-07-02 at 11 54 00" src="https://github.com/EvilHacker/BoxJoint/assets/174439488/d3b86eb9-f806-43f5-8b0f-04dbbe8f6dc5">

**Comment by basisvectors** [comment]
You're on the wrong repo, you're using the Finger Joint plugin (https://github.com/FlorianPommerening/FingerJoints) not the Box Joint plugin from this repo, as for what you're doing wrong with the finger joint plugin, the two bodies have to overlap for the finger joints to work.

**Comment by Khey426** [comment]
I just thought you changed the name, doh! Thanks.

From: ali ***@***.***>
Date: Sunday, 4 August 2024 at 13:30
To: EvilHacker/BoxJoint ***@***.***>
Cc: Karl Heydenrych ***@***.***>, Author ***@***.***>
Subject: Re: [EvilHacker/BoxJoint] I can't get this new release to work! (Issue #6)

You're on the wrong repo, you're using the Finger Joint plugin (https://github.com/FlorianPommerening/FingerJoints) not the Box Joint plugin from this repo, as for what you're doing wrong with the finger joint plugin, the two bodies have to overlap for the finger joints to work.

**Comment by EvilHacker** [comment]
I believe this issue is for another but similar add-in. This is not related to this `BoxJoint` add-in.
